- name: "Instalação do vim"
  apt: pkg=vim state=latest

- name: "Instalação do git"
  apt: pkg=git state=latest

- name: "Instalação do ufw"
  apt: pkg=ufw state=latest

- name: "Instalação do apache2"
  apt: pkg=apache2 state=latest

- name: "Adicionar um file de teste"
  copy: src=/Users/macz/Desktop/4ano/SDB/Ansible/apache_files/apache2.conf dest=/home/tiago96baptista/teste owner=root group=root mode=0666

- name: "Clone do repositorio do hotCRP"
  git:
    repo: 'https://github.com/kohler/hotcrp.git'
    dest:  /var/www/hotcrp
    update: no

- name: "Adicionar o file apache.conf devidamente configurado"
  copy: src=/Users/macz/Desktop/4ano/SDB/Ansible/apache_files/apache2.conf dest=/etc/apache2 owner=root group=root mode=0666

- name: "Adicionar o file 000-default.conf devidamente configurado"
  copy: src=/Users/macz/Desktop/4ano/SDB/Ansible/apache_files/sites-available/000-default.conf dest=/etc/apache2/sites-available owner=root group=root mode=0666

- name: "Adicionar o file default-ssl.conf devidamente configurado"
  copy: src=/Users/macz/Desktop/4ano/SDB/Ansible/apache_files/sites-available/default-ssl.conf dest=/etc/apache2/sites-available owner=root group=root mode=0666

- name: "Adicionar o file para o dominio do hotcrp devidamente configurado"
  copy: src=/Users/macz/Desktop/4ano/SDB/Ansible/apache_files/sites-available/hotcrp.dev.conf dest=/etc/apache2/sites-available owner=root group=root mode=0666

- name: "Adicionar o file hosts para permitir o acesso pelo ip da máquina"
  copy: src=/Users/macz/Desktop/4ano/SDB/Ansible/server/configs/hosts dest=/etc owner=root group=root mode=0666

- name: "Ir para a pasta dos sites-available e efetuar o link "
  command: chdir=/etc/apache2/sites-available a2ensite hotcrp.dev.conf

- name: "Adicionar o ficheiro com as opções da base de dados configurado"
  copy: src=/Users/macz/Desktop/4ano/SDB/Ansible/server/configs/options.php dest=/var/www/hotcrp/conf owner=root group=root mode=0666

- name: "Restart do apache2 para aplicar as configurações"
  service: name=apache2 state=restarted
