- name: "Instalação do git"
  apt: pkg=git state=latest

- name: "Instalação do ufw"
  apt: pkg=ufw state=latest

- name: "Clone do repositorio do hotCRP"
  git:
    repo: 'https://github.com/kohler/hotcrp.git'
    dest:  /home/tiago96baptista/hotcrp
    update: no

- name: "Instalação do mySQL-server"
  apt:
    name: "{{ item }}"
  with_items:
    - python-mysqldb
    - mysql-server

- name: "Adicionar o file das configs da base de dados"
  copy: src=/Users/macz/Desktop/4ano/SDB/Ansible/server/configs/mysqld.cnf dest=/etc/mysql/mysql.conf.d owner=root group=root mode=0666

- name: "Começar o MySQL service"
  action: service name=mysql state=started

- name: " Criar um user" 
  mysql_user:
    name: hotcrp
    password: hotcrp
    priv: '*.*:ALL'
    state: present
    host: 35.246.70.111

- name: "restart mysql"
  service: name=mysql
           enabled=yes
           state=restarted

- name: " Criar a base de dados" 
  mysql_db:
    name: hotcrp
    login_user: hotcrp
    login_host: 35.197.195.113 
    login_password: "hotcrp"

- name: Import DB 
  shell: mysql hotcrp < /home/tiago96baptista/hotcrp/src/schema.sql



