# Cria Um Disco Com Boot Para Ubuntu 16.04 LTS
- name: create a disk
  gcp_compute_disk:
      name: "{{ item }}"
      size_gb: 10
      source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
  register: disk
  loop: "{{ disks }}"

# Cria Uma Rede
- name: create a network
  gcp_compute_network:
      name: "sdb-network"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
  register: network

# Cria Um Endereço IP Externo Estático
- name: create a address
  gcp_compute_address:
      name: "{{ item }}"
      region: "{{ gcp_region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
  register: address
  loop: "{{ addresses }}"

- name: create an instance
  gcp_compute_instance:
    name: "{{ item.tag }}-{{ '%02d' | format(item.number) }}"
    machine_type: "{{ gcp_machine_type }}"
    metadata:
      startup-script:
        # - apt update -y
    tags:
      items: "{{ item.tag }}"
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disk.results[item.index-1] }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: External NAT
        nat_ip: "{{ address.results[item.index-1] }}"
        type: ONE_TO_ONE_NAT
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: instance
  loop: "{{ instances }}"