---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: gcp
      vars:
        gcp_zone: europe-west2-c
        gcp_region: europe-west2
        gcp_project: hotcrp
        gcp_cred_kind: serviceaccount
        gcp_cred_file: /Users/macz/Desktop/4ano/SDB/Ansible/server/hotcrp-30eb17bf7116.json
        gcp_machine_type: n1-standard-2
        source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts 
        scopes:
          - https://www.googleapis.com/auth/compute
        disk_size: 12
        disks:
          - disk-01
          - disk-02
        addresses:
          - addr-01
          - addr-02
        instances:
          - { index: 1, number: 1, tag: app }
          - { index: 2, number: 2, tag: database }

- hosts: app
  become: yes
  roles:
    - { role: webserver, address_data: "{{ groups['database'] }}" }

- hosts: database
  become: yes
  roles:
    - { role: database, address_back: "{{ groups['app'] }}", address_data: "{{ groups['database'] }}"}